/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package valentinesDay;



/**
 *
 * @author hehua8751
 */

import javax.swing.JFrame;
public class Girls extends javax.swing.JFrame {

    /**
     * Creates new form valentines
     */
    public Girls() {
        initComponents();
        initialSetUp();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        explanationOneLabel = new javax.swing.JLabel();
        letterOneLabel = new javax.swing.JLabel();
        continueTwoButton = new javax.swing.JButton();
        letterTwoLabel = new javax.swing.JLabel();
        explanationTwoLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        explanationOneLabel.setFont(new java.awt.Font("Three Arrows", 0, 18)); // NOI18N
        explanationOneLabel.setText("\"A Boy Can Do Everything For Girls\"");

        letterOneLabel.setFont(new java.awt.Font("Three Arrows", 0, 18)); // NOI18N
        letterOneLabel.setText("\"A, B, C, D, E, F, G\"");

        continueTwoButton.setText("Continue");
        continueTwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueTwoButtonActionPerformed(evt);
            }
        });

        letterTwoLabel.setFont(new java.awt.Font("Three Arrows", 0, 18)); // NOI18N
        letterTwoLabel.setText("\"H, I, J, K\"");

        explanationTwoLabel.setFont(new java.awt.Font("Three Arrows", 0, 18)); // NOI18N
        explanationTwoLabel.setText("\"He Is Just Kidding\"");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(continueTwoButton)
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(letterOneLabel)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(letterTwoLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(explanationTwoLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(183, 183, 183))
                                .addComponent(explanationOneLabel))
                            .addContainerGap(38, Short.MAX_VALUE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addComponent(continueTwoButton)
                .addGap(96, 96, 96))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(letterOneLabel)
                    .addGap(1, 1, 1)
                    .addComponent(explanationOneLabel)
                    .addGap(16, 16, 16)
                    .addComponent(letterTwoLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(explanationTwoLabel)
                    .addContainerGap(177, Short.MAX_VALUE)))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueTwoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueTwoButtonActionPerformed
        continueTwo();
        
    }//GEN-LAST:event_continueTwoButtonActionPerformed

    
    private void continueTwo()
    {
        String text = continueTwoButton.getText();
        
        if (text == "Continue")
        {
        letterTwoLabel.setVisible(true);
        explanationTwoLabel.setVisible(true);
        continueTwoButton.setText("Back");
        }
        else
        {
            homePage();
        }
        
    }
    
    private void homePage()
    {
       this.setVisible(false);
       new ValentinesDay.setVisible(false);
       new ValentinesDay().setVisible(true);
    }
    
    private void initialSetUp()
    {
        letterOneLabel.setVisible(true);
        explanationOneLabel.setVisible(true);
        continueTwoButton.setVisible(true);
        letterTwoLabel.setVisible(false);
        explanationTwoLabel.setVisible(false);
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Girls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Girls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Girls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Girls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Girls().setVisible(true);
            }
        });
    }
 static class setVisible {

        public setVisible(boolean b) {
        }
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continueTwoButton;
    private javax.swing.JLabel explanationOneLabel;
    private javax.swing.JLabel explanationTwoLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel letterOneLabel;
    private javax.swing.JLabel letterTwoLabel;
    // End of variables declaration//GEN-END:variables
}
   


